version: '3'

tasks:
  default:
    desc: 全てのタスクを実行（lint, fmt, test, build）
    cmds:
      - task: lint
      - task: fmt
      - task: test
      - task: build

  build:
    desc: アプリケーションとツールをビルド
    cmds:
      - echo "Building..."
      - mkdir -p bin
      - go build -o bin/mozisu-mcp-server ./cmd/mcpserver
      - go build -o bin/charcount ./cmd/charcount
      - go build -o bin/webserver ./cmd/webserver
      - echo "Build completed."

  release:
    desc: リリース用のビルドを実行
    cmds:
      - echo "Building release version..."
      - mkdir -p build
      - go build -ldflags="-s -w" -o build/mozisu-mcp-server ./cmd/mcpserver
      - go build -ldflags="-s -w" -o build/charcount ./cmd/charcount
      - go build -ldflags="-s -w" -o build/webserver ./cmd/webserver
      - echo "Release build completed successfully!"

  test:
    desc: テストを実行
    cmds:
      - echo "Running tests..."
      - go test -v ./...
      - echo "Tests completed."

  lint:
    desc: リンターを実行
    cmds:
      - echo "Running linter..."
      - cmd: |
          if ! command -v golangci-lint &> /dev/null; then
            echo "golangci-lint not found, installing..."
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          fi
          golangci-lint run ./...
      - echo "Lint completed."
    silent: false

  lint-fix:
    desc: リンターを実行して問題を自動修正
    cmds:
      - echo "Running linter with auto-fix..."
      - cmd: |
          if ! command -v golangci-lint &> /dev/null; then
            echo "golangci-lint not found, installing..."
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          fi
          golangci-lint run --fix
      - echo "Lint with auto-fix completed."
    silent: false

  fmt:
    desc: コードをフォーマット
    cmds:
      - echo "Formatting code..."
      - gofmt -s -w .
      - cmd: |
          if ! command -v goimports &> /dev/null; then
            echo "goimports not found, installing..."
            go install golang.org/x/tools/cmd/goimports@latest
          fi
          goimports -w .
      - echo "Format completed."

  clean:
    desc: ビルド成果物を削除
    cmds:
      - echo "Cleaning..."
      - rm -rf bin/ build/
      - echo "Clean completed."
